name: Build and Upload .NET Framework Web App

on:
  push:
    branches: [ master ]  # Trigger on pushes to master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      run: nuget restore WebApplication3.sln

    - name: Build Project to Output Folder
      run: |
        msbuild WebApplication3.csproj `
          /p:Configuration=Release `
          /p:OutputPath=Published\

    - name: List Published Folder (Debugging)
      run: |
        echo "Contents of Published folder:"
        Get-ChildItem -Recurse -Path Published

    - name: Upload Published App as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: Published/
